<?php
/**
 * أرشيف الأخبار والمقالات.
 *
 * @package Alzaherah
 * @since   4.2.0
 */

defined( 'ABSPATH' ) || exit;

$alz_category      = get_queried_object();
$alz_category_slug = $alz_category instanceof WP_Term ? $alz_category->slug : '';
$alz_is_news       = 'alzaherah-news' === $alz_category_slug;
$alz_is_articles   = 'alzaherah-articles' === $alz_category_slug;
$alz_archive_title = $alz_is_news ? __( 'أخبارنا', 'alzaherah' ) : ( $alz_is_articles ? __( 'مقالاتنا', 'alzaherah' ) : single_cat_title( '', false ) );
$alz_archive_kicker = $alz_is_news ? __( 'آخر مستجدات المركز', 'alzaherah' ) : ( $alz_is_articles ? __( 'معرفة قابلة للتطبيق', 'alzaherah' ) : __( 'مكتبة المركز', 'alzaherah' ) );
$alz_archive_copy  = $alz_is_news
	? __( 'تابع أخبار المركز وشراكاته وبرامجه ومبادراته التدريبية والمجتمعية.', 'alzaherah' )
	: ( $alz_is_articles
		? __( 'مقالات مهنية تساعدك على تطوير مهاراتك والاستفادة من فرص التعلم المستمر.', 'alzaherah' )
		: wp_strip_all_tags( category_description() ) );

/**
 * تجهيز صورة بطاقة الأرشيف من مكتبة الوسائط أو الشعار المحلي فقط.
 *
 * @param int $post_id معرف المنشور.
 * @return array{type:string,html:string,url:string}
 */
$alz_archive_image = static function ( $post_id ) {
	$thumbnail_id = get_post_thumbnail_id( $post_id );
	if ( $thumbnail_id ) {
		return array(
			'type' => 'local',
			'html' => (string) wp_get_attachment_image(
				$thumbnail_id,
				'medium_large',
				false,
				array(
					'alt'      => '',
					'loading'  => 'lazy',
					'decoding' => 'async',
				)
			),
			'url'  => '',
		);
	}

	return array(
		'type' => 'placeholder',
		'html' => '',
		'url'  => function_exists( 'alzaherah_local_placeholder_image_url' ) ? alzaherah_local_placeholder_image_url() : ( get_template_directory_uri() . '/assets/logo-mark.png' ),
	);
};

get_header();
?>

<main id="main" class="alz3-content-archive" role="main">
	<section class="alz3-archive-hero" aria-labelledby="archive-title">
		<div class="container">
			<span class="eyebrow"><?php echo esc_html( $alz_archive_kicker ); ?></span>
			<h1 class="section-title" id="archive-title"><?php echo esc_html( $alz_archive_title ); ?></h1>
			<?php if ( $alz_archive_copy ) : ?><p><?php echo esc_html( $alz_archive_copy ); ?></p><?php endif; ?>
		</div>
	</section>

	<section class="section alz3-archive-results" aria-label="<?php echo esc_attr( $alz_archive_title ); ?>">
		<div class="container">
			<?php if ( have_posts() ) : ?>
				<div class="alz3-content-grid alz3-archive-grid">
					<?php while ( have_posts() ) : the_post(); ?>
						<?php $alz_card_image = $alz_archive_image( get_the_ID() ); ?>
						<article <?php post_class( 'alz3-content-card' ); ?>>
							<a class="alz3-content-card-link" href="<?php the_permalink(); ?>">
								<span class="alz3-content-media" aria-hidden="true">
									<?php if ( 'local' === $alz_card_image['type'] ) : ?>
										<?php echo $alz_card_image['html']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by wp_get_attachment_image(). ?>
									<?php else : ?>
										<span class="alz3-content-placeholder"><img src="<?php echo esc_url( $alz_card_image['url'] ); ?>" alt="" width="80" height="81" loading="lazy" decoding="async"><span><?php esc_html_e( 'مركز الزاهرة للتدريب', 'alzaherah' ); ?></span></span>
									<?php endif; ?>
								</span>
								<span class="alz3-content-body">
									<time datetime="<?php echo esc_attr( get_the_date( 'c' ) ); ?>"><?php echo esc_html( get_the_date( 'Y/m/d' ) ); ?></time>
									<h2><?php the_title(); ?></h2>
									<span class="alz3-content-excerpt"><?php echo esc_html( wp_trim_words( wp_strip_all_tags( get_the_excerpt() ), 28, '…' ) ); ?></span>
									<span class="alz3-content-more"><?php echo esc_html( $alz_is_news ? __( 'قراءة الخبر', 'alzaherah' ) : __( 'قراءة المقال', 'alzaherah' ) ); ?> <?php echo alzaherah_ui_arrow(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></span>
								</span>
							</a>
						</article>
					<?php endwhile; ?>
				</div>

				<?php
				the_posts_pagination(
					array(
						'mid_size'  => 1,
						'prev_text' => __( 'السابق', 'alzaherah' ),
						'next_text' => __( 'التالي', 'alzaherah' ),
						'screen_reader_text' => __( 'التنقل بين صفحات المحتوى', 'alzaherah' ),
					)
				);
				?>
			<?php else : ?>
				<div class="alz3-content-empty">
					<h2><?php esc_html_e( 'لا يوجد محتوى منشور حاليًا', 'alzaherah' ); ?></h2>
					<p><?php esc_html_e( 'ستظهر المواد الجديدة هنا فور نشرها واعتمادها.', 'alzaherah' ); ?></p>
					<a class="btn btn-primary" href="<?php echo esc_url( home_url( '/' ) ); ?>"><?php esc_html_e( 'العودة إلى الرئيسية', 'alzaherah' ); ?></a>
				</div>
			<?php endif; ?>
		</div>
	</section>
</main>

<?php get_footer(); ?>
