<?php
/**
 * قالب الخبر أو المقال المفرد.
 *
 * @package Alzaherah
 * @since   4.2.0
 */

defined( 'ABSPATH' ) || exit;

$alz_post_id     = get_queried_object_id();
$alz_is_news     = has_category( 'alzaherah-news', $alz_post_id );
$alz_is_article  = has_category( 'alzaherah-articles', $alz_post_id );
$alz_content_label = $alz_is_news ? __( 'أخبارنا', 'alzaherah' ) : ( $alz_is_article ? __( 'مقالاتنا', 'alzaherah' ) : __( 'مكتبة المركز', 'alzaherah' ) );
$alz_content_term  = get_category_by_slug( $alz_is_news ? 'alzaherah-news' : ( $alz_is_article ? 'alzaherah-articles' : '' ) );
$alz_archive_url   = $alz_content_term ? get_category_link( $alz_content_term->term_id ) : home_url( '/' );
$alz_archive_url   = is_wp_error( $alz_archive_url ) ? home_url( '/' ) : $alz_archive_url;

$alz_single_image = array(
	'type' => 'placeholder',
	'html' => '',
	'url'  => function_exists( 'alzaherah_local_placeholder_image_url' ) ? alzaherah_local_placeholder_image_url() : ( get_template_directory_uri() . '/assets/logo-mark.png' ),
);
$alz_thumbnail_id = get_post_thumbnail_id( $alz_post_id );

if ( $alz_thumbnail_id ) {
	$alz_single_image = array(
		'type' => 'local',
		'html' => (string) wp_get_attachment_image(
			$alz_thumbnail_id,
			'large',
			false,
			array(
				'alt'      => '',
				'decoding' => 'async',
			)
		),
		'url'  => '',
	);
}

get_header();
?>

<main id="main" class="alz3-single-content" role="main">
	<?php while ( have_posts() ) : the_post(); ?>
		<article <?php post_class( 'alz3-single-article' ); ?>>
			<header class="alz3-single-hero">
				<div class="container alz3-single-hero-inner">
					<a class="alz3-single-back" href="<?php echo esc_url( $alz_archive_url ); ?>"><?php echo alzaherah_ui_arrow( 'back' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?> <?php echo esc_html( $alz_content_label ); ?></a>
					<span class="eyebrow"><?php echo esc_html( $alz_is_news ? __( 'خبر من المركز', 'alzaherah' ) : __( 'من مكتبة الزاهرة', 'alzaherah' ) ); ?></span>
					<h1><?php the_title(); ?></h1>
					<div class="alz3-single-meta">
						<time datetime="<?php echo esc_attr( get_the_date( 'c' ) ); ?>"><?php echo esc_html( get_the_date( 'Y/m/d' ) ); ?></time>
						<?php if ( has_category() ) : ?><span><?php echo wp_kses_post( get_the_category_list( '، ' ) ); ?></span><?php endif; ?>
					</div>
				</div>
			</header>

			<div class="container alz3-single-layout">
				<figure class="alz3-single-media<?php echo 'placeholder' === $alz_single_image['type'] ? ' is-placeholder' : ''; ?>" aria-hidden="true">
					<?php if ( 'local' === $alz_single_image['type'] ) : ?>
						<?php echo $alz_single_image['html']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by wp_get_attachment_image(). ?>
					<?php else : ?>
						<span class="alz3-content-placeholder"><img src="<?php echo esc_url( $alz_single_image['url'] ); ?>" alt="" width="120" height="122" decoding="async"><span><?php esc_html_e( 'مركز الزاهرة للتدريب', 'alzaherah' ); ?></span></span>
					<?php endif; ?>
				</figure>

				<div class="alz3-single-body entry-content">
					<?php
					the_content();
					wp_link_pages(
						array(
							'before' => '<nav class="page-links" aria-label="' . esc_attr__( 'صفحات المحتوى', 'alzaherah' ) . '">',
							'after'  => '</nav>',
						)
					);
					?>
				</div>

				<?php
				$alz_previous = get_previous_post( true, '', 'category' );
				$alz_next     = get_next_post( true, '', 'category' );
				if ( $alz_previous || $alz_next ) :
					?>
					<nav class="alz3-single-post-nav" aria-label="<?php esc_attr_e( 'المحتوى السابق والتالي', 'alzaherah' ); ?>">
						<?php if ( $alz_previous ) : ?>
							<a href="<?php echo esc_url( get_permalink( $alz_previous ) ); ?>"><span><?php esc_html_e( 'السابق', 'alzaherah' ); ?></span><strong><?php echo esc_html( get_the_title( $alz_previous ) ); ?></strong></a>
						<?php endif; ?>
						<?php if ( $alz_next ) : ?>
							<a href="<?php echo esc_url( get_permalink( $alz_next ) ); ?>"><span><?php esc_html_e( 'التالي', 'alzaherah' ); ?></span><strong><?php echo esc_html( get_the_title( $alz_next ) ); ?></strong></a>
						<?php endif; ?>
					</nav>
				<?php endif; ?>

				<div class="alz3-single-cta">
					<div><strong><?php echo esc_html( $alz_content_label ); ?></strong><span><?php esc_html_e( 'استكشف المزيد من أخبار المركز ومحتواه المهني.', 'alzaherah' ); ?></span></div>
					<a class="btn btn-primary" href="<?php echo esc_url( $alz_archive_url ); ?>"><?php esc_html_e( 'عرض جميع المواد', 'alzaherah' ); ?></a>
				</div>
			</div>
		</article>
	<?php endwhile; ?>
</main>

<?php get_footer(); ?>
